### ISSUE TITLE
Archive this blog

### ISSUE THREAD

**Issue by luiarthur** [luiarthur/luiarthur.github.io#1]
I would like to archive this blog, and make a new, leaner, version of my blog.

I would like the blog to cover topics of computing in statistics. For example,

- Variational Inference
- MCMC in different languages
- HMC
- Julia, R, Python, Scala, C++
- VIM / TMUX

Other kinds of example code should be kept in my archive or other sandbox repos.

# TODO:
- [ ] archive this blog, but still make it accessible as a github page?
- [ ] make a new blog
    - [ ] use disqus for commenting
    - [ ] use katex (or mathjax if katex doesn't work)
            - [ ] use a `.min.js` for stability and reliability, despite speed of downloads
    - [ ] put new content
